Repository NYPL/dxp-react-search, pull requests merged in 2020-10, with the labels that each got.

#69 RENO-1741 - Mobile "View on Map" Fix
  CHANGELOG.md
  src/components/location-finder/Location/index.js
  src/components/location-finder/Locations/Locations.scss
  src/components/location-finder/Map/index.js
  src/pages/locations/index.js
Labels: Changes Requested

#73 RENO-1633: Map Markers on Click Should Scroll to Location
  CHANGELOG.md
  src/components/location-finder/Map/index.js
Labels: Needs Review

#75 RENO-1802 - Today's Hours display stripping out minutes
  CHANGELOG.md
  src/components/location-finder/Location/index.js
Labels: Ship It!

#60 RENO-1708: Set Unqiue Asset Prefix for Reverse Proxy
  .env.example
  CHANGELOG.md
  README.md
  next.config.js
  provisioning/set-env
Labels: Needs Review

#77 RENO-1830: All Day Closings Accommodate Hours + Mins
  CHANGELOG.md
  package-lock.json
  package.json
  src/apollo/server/datasources/RefineryApi.js
  src/utils/checkAlertsOpenStatus.js
  src/utils/checkAlertsOpenStatus.test.js
  src/utils/filterByOpenNow.js
Labels: Needs Review
