Repository NYPL/dxp-react-search, pull requests merged in 2020-08, with the labels that each got.

#5 RENO-1549: Location Finder: Build "Right Rail" Component
  package.json
  src/components/location-finder/RightRail/RightRail.scss
  src/components/location-finder/RightRail/content.js
  src/components/location-finder/RightRail/index.js
  src/pages/location-finder/index.js
  src/styles/main.scss
Labels: Changes Requested

#7 RENO-1551 - build bottom promo components
  src/components/location-finder/BottomPromo/BottomPromo.scss
  src/components/location-finder/BottomPromo/content.js
  src/components/location-finder/BottomPromo/index.js
  src/pages/location-finder/index.js
  src/styles/main.scss
Labels: Ship It!

#9 RENO-1548 Welcome Hero Component
  package-lock.json
  package.json
  src/components/location-finder/Hero/Hero.scss
  src/components/location-finder/Hero/content.js
  src/components/location-finder/Hero/index.js
  src/pages/location-finder/index.js
  src/styles/breakpoints/_breakpoints.scss
  src/styles/main.scss
Labels: Ship It!

#10 RENO-1550 build breadcrumb component
  package-lock.json
  package.json
  src/components/shared/layouts/Main.js
Labels: Ship It!

#11 RENO-1572 - Location component accessibility icons
  src/components/location-finder/Location/Location.scss
  src/components/location-finder/Location/index.js
  src/styles/main.scss
Labels: Ship It!

#13 RENO-1577 - bottom promo component update logos
  package.json
  src/components/location-finder/BottomPromo/BottomPromo.scss
  src/components/location-finder/BottomPromo/content.js
  src/components/location-finder/BottomPromo/index.js
Labels: Changes Requested

#20 RENO-1588: Cleanup SCSS for Location(s) components
  src/components/location-finder/BottomPromo/BottomPromo.scss
  src/components/location-finder/Hero/Hero.scss
  src/components/location-finder/Location/Location.scss
  src/components/location-finder/Locations/Locations.scss
  src/components/location-finder/RightRail/RightRail.scss
  src/components/location-finder/SearchHeader/SearchHeader.scss
  src/pages/location-finder/index.js
  src/styles/base/_breakpoints.scss
  src/styles/base/_mixins.scss
  src/styles/main.scss
  src/styles/space/_space-stack.scss
Labels: Ship It!

#15 RENO-1545: Setup Basic Testing
  .babelrc
  jest.config.js
  package-lock.json
  package.json
  src/components/location-finder/BottomPromo/BottomPromo.js
  src/components/location-finder/BottomPromo/BottomPromo.test.js
  src/components/location-finder/BottomPromo/index.js
  src/components/location-finder/Hero/Hero.js
  src/components/location-finder/Hero/Hero.test.js
  src/components/location-finder/Hero/index.js
  src/components/location-finder/RightRail/RightRail.js
  src/components/location-finder/RightRail/RightRail.test.js
  src/components/location-finder/RightRail/index.js
  testHelper/browser.js
Labels: Needs Review

#24 RENO-1606 Fix Deployment Builds
  .travis.yml
  provisioning/deploy
Labels: Ship It!

#26 RENO-1608 change hero component image
  src/components/location-finder/Hero/Hero.js
  src/components/location-finder/Hero/Hero.scss
  src/components/location-finder/HeroImage/HeroImage.js
Labels: Ship It!

#29 RENO-1618 - Location Finder VQA
  src/components/location-finder/BottomPromo/BottomPromo.scss
  src/components/location-finder/Location/Location.scss
  src/components/location-finder/Location/index.js
  src/components/location-finder/RightRail/RightRail.scss
  src/components/location-finder/SearchForm/SearchForm.scss
  src/components/location-finder/SearchHeader/SearchHeader.scss
  src/components/location-finder/SearchHeader/index.js
Labels: Ship It!

#37 RENO-1617 - Location Finder - add favicon
  public/favicon.ico
  src/components/location-finder/Meta/Meta.js
Labels: Ship It!

#41 RENO-1657: Setup GA Tracking
  .env.example
  provisioning/set-env
  src/pages/_document.js
Labels: Ship It!

#46 RENO 1641-1634 Location Finder VQA
  src/components/location-finder/Location/Location.scss
  src/components/location-finder/Locations/Locations.scss
  src/styles/base/_mixins.scss
Labels: Needs Review

#43 RENO-1677: Open Now Filter Shows Locations That Are Closed
  package-lock.json
  package.json
  src/apollo/server/datasources/RefineryApi.js
  src/components/location-finder/Locations/Locations.js
  src/utils/checkAlertsOpenStatus.js
  src/utils/filterByOpenNow.js
Labels: Review in Progress
