Repository NYPL/dxp-react-search, pull requests merged in 2020-09, with the labels that each got.

#51 RENO-1681 & 1682
  public/robots.txt
  src/pages/index.js
  src/pages/locations/index.js
Labels: Ship It!

#56 RENO-1691: Use .env variable for allowed origin
  .env.example
  provisioning/set-env
  src/pages/api/graphql.js
Labels: Needs Review

#50 RENO-1651: DS 0.14.0 Upgrade && Fixes for W3 Validation Errors
  next.config.js
  package-lock.json
  package.json
  src/components/location-finder/BottomPromo/BottomPromo.js
  src/components/location-finder/BottomPromo/BottomPromo.scss
  src/components/location-finder/Hero/Hero.scss
  src/components/location-finder/Locations/Locations.scss
  src/components/location-finder/SearchAutoSuggest/SearchAutoSuggest.scss
  src/components/location-finder/SearchForm/SearchForm.js
  src/components/location-finder/SearchForm/SearchForm.scss
  src/components/location-finder/SearchHeader/SearchHeader.scss
  src/styles/base/_base.scss
  src/styles/base/_mixins.scss
  src/styles/main.scss
Labels: Needs Review

#16 RENO-1587: Loading Skeleton
  src/components/location-finder/Locations/Locations.js
  src/components/shared/LoadingSkeleton/LoadingSkeleton.js
  src/components/shared/LoadingSkeleton/LoadingSkeleton.scss
  src/components/shared/LoadingSkeleton/index.js
  src/styles/main.scss
Labels: Changes Requested

#62 RENO-1642: Remove Pagination From Desktop
  CHANGELOG.md
  src/components/location-finder/Locations/Locations.js
  src/components/location-finder/Locations/LocationsPagination.js
  src/hooks/useWindowSize.js
Labels: Needs Review
