Repository NYPL/dxp-react-search, pull requests merged in 2022-10, with the labels that each got.

#330 RENO-3068: Update Individual PressRelease UX
  src/components/press-releases/PressRelease/PressRelease.tsx
Labels: Needs Review

#331 RENO-3087: Wire Up Subtitle and Meta Description Fields to individual PressRelease
  src/apollo/client/fragments/pressFields.js
  src/apollo/server/resolvers/pressReleaseResolver.js
  src/apollo/server/type-defs/press.js
  src/components/press-releases/PressRelease/PressRelease.tsx
Labels: Ship It!

#334 Section Fronts: Give Sandbox
  src/apollo/client/fragments/blogFields.js
  src/apollo/server/resolvers/index.js
  src/apollo/server/resolvers/sectionFrontResolver.js
  src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
  src/apollo/server/resolvers/utils/resolveParagraphTypes.ts
  src/apollo/server/schema.js
  src/apollo/server/type-defs/sectionFront.js
  src/apollo/server/type-defs/shared.js
  src/components/section-fronts/Donation/Donation.test.tsx
  src/components/section-fronts/Donation/Donation.tsx
  src/components/section-fronts/Donation/DonationAmountInput.tsx
  src/components/section-fronts/Donation/DonationLinkButton.tsx
  src/components/section-fronts/Donation/index.ts
  src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
  src/components/section-fronts/SectionFrontPage/index.ts
  src/components/shared/CardGrid/Card.tsx
  src/components/shared/CardGrid/CardGrid.tsx
  src/components/shared/CardGrid/CardGridHeader.tsx
  src/components/shared/CardGrid/CardGridSkeletonLoader.tsx
  src/components/shared/CardGrid/index.ts
  src/components/shared/ContentComponents/CardList.tsx
  src/components/shared/ContentComponents/getReactComponent.tsx
  src/components/shared/Link/NextDsLink.tsx
  src/components/shared/PreviewModeNotification/PreviewModeNotification.tsx
  src/components/shared/PreviewModeNotification/index.ts
  src/pages/[...slug].tsx
  src/pages/api/exit-preview.ts
  src/pages/api/preview.ts
  src/pages/api/revalidate.ts
Labels: Review in Progress
